name: waterdo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_local_notifications: ^17.0.0
  lottie: ^3.1.2
  path_provider: ^2.1.2
  intl: ^0.19.0
  google_sign_in: ^6.2.1
  uuid: ^4.5.1

  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  firebase_ui_auth: ^1.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.9
  hive_generator: ^2.0.1

dependency_overrides:
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/pop.json
    - assets/lottie/empty.json
    - assets/images/google_logo.png

  plugin:
    platforms:
      windows:
        default_package: none
