// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYTfgw8W_vb_6MH4jJ5EQfKSwCS1g7u0M',
    appId: '1:13279865396:web:c6bf907e400ebcf57b3861',
    messagingSenderId: '13279865396',
    projectId: 'waterdo-6c5b5',
    authDomain: 'waterdo-6c5b5.firebaseapp.com',
    storageBucket: 'waterdo-6c5b5.firebasestorage.app',
    measurementId: 'G-Y6WHBSLX3J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwcHGn5qvigLSx6bK-2PMiwDrDtR8bBsI',
    appId: '1:13279865396:android:c48814d6a02af89c7b3861',
    messagingSenderId: '13279865396',
    projectId: 'waterdo-6c5b5',
    storageBucket: 'waterdo-6c5b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTUoJCEyQHyOqelG22_uN2nCHEisU9urM',
    appId: '1:13279865396:ios:b749dd7a830085fb7b3861',
    messagingSenderId: '13279865396',
    projectId: 'waterdo-6c5b5',
    storageBucket: 'waterdo-6c5b5.firebasestorage.app',
    iosClientId: '13279865396-q4dcn28oe6f0hhlk4u1lhgcncvrhgp3m.apps.googleusercontent.com',
    iosBundleId: 'com.example.waterdo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTUoJCEyQHyOqelG22_uN2nCHEisU9urM',
    appId: '1:13279865396:ios:b749dd7a830085fb7b3861',
    messagingSenderId: '13279865396',
    projectId: 'waterdo-6c5b5',
    storageBucket: 'waterdo-6c5b5.firebasestorage.app',
    iosClientId: '13279865396-q4dcn28oe6f0hhlk4u1lhgcncvrhgp3m.apps.googleusercontent.com',
    iosBundleId: 'com.example.waterdo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYTfgw8W_vb_6MH4jJ5EQfKSwCS1g7u0M',
    appId: '1:13279865396:web:10d8ebfe7a13fb867b3861',
    messagingSenderId: '13279865396',
    projectId: 'waterdo-6c5b5',
    authDomain: 'waterdo-6c5b5.firebaseapp.com',
    storageBucket: 'waterdo-6c5b5.firebasestorage.app',
    measurementId: 'G-144SEZKL8W',
  );
}
